# 1- Tipos e Tamanho

Transformando listas em arrays

In [6]:
import numpy as np

In [7]:
a = [1,2,3]
b = [[4.,5.,6.],[7.,8.,9.]]

In [8]:
#Transformando em Array e modificando tamanho
a = np.array(a, dtype='int64')
b = np.array(b)

print(a)
print(b)

[1 2 3]
[[4. 5. 6.]
 [7. 8. 9.]]


In [9]:
#Formato do Array
b.shape

(2, 3)

In [10]:
#Verificando Dimensionalidade
b.ndim

2

Tipos e Tamanhos

In [11]:
#Obter tipo
a.dtype

dtype('int64')

In [12]:
a.itemsize

8

In [13]:
b.dtype

dtype('float64')

In [14]:
b.itemsize

8

In [15]:
#Tamanho total
a.nbytes

24

In [16]:
#Tamanho total
b.nbytes

48

# 2- Inicializando Arrays

In [17]:
np.zeros((2,2), dtype='int16')

array([[0, 0],
       [0, 0]], dtype=int16)

In [18]:
test = np.ones((2,2,3), dtype='int64')
print(test)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [19]:
test.ndim

3

In [20]:
np.full((2,2), 100, dtype='int32')

array([[100, 100],
       [100, 100]])

In [21]:
np.full_like(test, 5, dtype='int64')

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]], dtype=int64)

Preenchendo com valores aleatórios entre 0 e 1

In [22]:
np.random.rand(4,2)

array([[0.4900932 , 0.65136695],
       [0.92926542, 0.29327189],
       [0.05219148, 0.6253187 ],
       [0.68039189, 0.6355021 ]])

In [23]:
np.random.random_sample(test.shape)

array([[[0.30655502, 0.09463086, 0.50985975],
        [0.25779868, 0.37015838, 0.01380132]],

       [[0.73479806, 0.3338826 , 0.47893302],
        [0.41326869, 0.5226467 , 0.38438908]]])

Preenchendo com valores aleatórios inteiros

In [24]:
np.random.randint(0,100, size=(2,2))

array([[26, 50],
       [44, 20]])

In [25]:
np.random.randint(0,100, size=(test.shape))

array([[[37, 19, 90],
        [87, 55, 89]],

       [[81, 18, 37],
        [12, 80, 98]]])

Repetir uma Array

In [26]:
lista = [1,2,3]
array = np.array(lista)
np.repeat(array, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

# 3- Fatiamento, Cópias e Índices

In [27]:
a = np.ones((5,5), dtype='int16')
b = np.zeros((3,3), dtype='int16')
c = np.random.randint(0,100, size=(1,1), dtype='int16')

a[1:-1, 1:-1] = b
a[2,2] = c
a

C:\Users\Gabriel\AppData\Local\Temp\ipykernel_13140\34539391.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  a[2,2] = c


array([[ 1,  1,  1,  1,  1],
       [ 1,  0,  0,  0,  1],
       [ 1,  0, 20,  0,  1],
       [ 1,  0,  0,  0,  1],
       [ 1,  1,  1,  1,  1]], dtype=int16)

In [28]:
#Utilizar copy()
a = np.full_like(a, 100)
b = a.copy()
b

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]], dtype=int16)

# 4- Stats

In [29]:
b = np.array([[4.,5.,6.],[7.,8.,9.], [10.,11.,12]], dtype='int16')

Min()

In [30]:
print(f'O mínimo total é: {np.min(b)}')
print(f'A menor array é: {np.min(b, axis=0)}')
print(f'O mínimo local unitário é: {np.min(b, axis=1)}')

O mínimo total é: 4
A menor array é: [4 5 6]
O mínimo local unitário é: [ 4  7 10]


Max()

In [31]:
print(f'O mínimo total é: {np.max(b)}')
print(f'A menor array é: {np.max(b, axis=0)}')
print(f'O mínimo local unitário é: {np.max(b, axis=1)}')

O mínimo total é: 12
A menor array é: [10 11 12]
O mínimo local unitário é: [ 6  9 12]


In [32]:
np.sum(b)

72

In [33]:
np.mean(b)

8.0

In [34]:
np.median(b)

8.0

# 5- Reorganizando Arrays

In [35]:
b = np.array([[4.,5.,6.],[7.,8.,9.]])
np.shape(b)

(2, 3)

In [36]:
b.reshape((6,1))

array([[4.],
       [5.],
       [6.],
       [7.],
       [8.],
       [9.]])

VStacks

In [37]:
v1 = np.ones((1,4))
v2 = np.zeros((1,4))

np.vstack((v1,v2))

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.]])

HStack

In [38]:
np.hstack((v1,v2))

array([[1., 1., 1., 1., 0., 0., 0., 0.]])

# 6- Carregando dados com Numpy 

Diferenças no armazenamento da memória

In [48]:
filedata = np.loadtxt('data.txt', delimiter=',')
filedata.astype('int16') 
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [62]:
filedata = np.loadtxt('data.txt', delimiter=',')
filedata = filedata.astype('int16') 
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int16)

Booleans

In [63]:
data = filedata > 100
data

array([[False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [64]:
filedata[data]

array([196, 766, 999], dtype=int16)